name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install Dependencies
        run: pnpm i
      - name: Run lint
        run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install Dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm run test
